### ISSUE TITLE
Display closing bracket adornment

### ISSUE THREAD

**Issue by ionoy** [AmmyUI/AmmyUI#1]
JSON-like languages have one common problem, namely closing bracket trail. 
I'm talking about this:

```
        }
      }
    }
  }
}
```

It can be very difficult to understand which bracket corresponds to particular node.
My suggestions looks something like this:

![end-tags](https://cloud.githubusercontent.com/assets/592624/21645563/3901a6dc-d29b-11e6-83ac-8dac685782a3.png)

We would display node type + name at the closing bracket.
Note, that when line is selected adornment gets hidden.

**Comment by ionoy** [comment]
Done! New version will be released by the end of the week. Note, that next update will require updating both NuGet package and VS extension.

**Comment by chrischu** [comment]
Would also be cool if the blocks were also collapsible (like #regions in C#).

**Comment by ionoy** [comment]
I'll create an additional issue for that
