### ISSUE TITLE
Xamarin Forms Quickstart won't compile

### ISSUE THREAD

**Issue by WasserEsser** [AmmyUI/AmmyUI#100]
Hi,

I followed your Xamarin Forms Quickstart Guide and tried to compile it.
However, Ammy is unable to compile the source due to a NullReferenceException being thrown.

> 1>------ Erstellen gestartet: Projekt: AmmyXamarinApp.Android, Konfiguration: Debug Any CPU ------
1><Default>(1,1,1,1): error : Ammy compilation error: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
1><Default>(1,1,1,1): error :    bei DotNet.TopConstructedTypeSymbol.EvalProperties(DependentPropertyEvalContext context)
1><Default>(1,1,1,1): error :    bei Ammy.Backend.ReflectionBackend.CreateConstructedTypeSymbol(Type type)
1><Default>(1,1,1,1): error :    bei Ammy.Backend.ReflectionBackend.GetTypeSymbol(Type type)
1><Default>(1,1,1,1): error :    bei Ammy.Backend.ReflectionBackend.InitBaseTypeSet()
1><Default>(1,1,1,1): error :    bei Ammy.Backend.ReflectionBackend.LoadExternalSymbols(IEnumerable`1 libs, String libPath, ICompilerMessages compilerMessages, DependentPropertyEvalContext context)
1><Default>(1,1,1,1): error :    bei Ammy.Language.Start.RefreshReferences(Project project)
1><Default>(1,1,1,1): error :    bei Ammy.Language.Start.RefreshReferences(CancellationToken _cancellationToken, Project project)
1><Default>(1,1,1,1): error :    bei Ammy.Build.AmmyProject.RefreshReferences()
1><Default>(1,1,1,1): error :    bei Ammy.Build.AmmyCompiler.Compile(AmmyProject project, Boolean generateMetaFile, Boolean needBamlGeneration, Boolean needUpdate)

I installed VS 2017 with Xamarin, created a new project, installed Ammy.XamarinForms, added a new page to my shared project (AmmyXamarinApp) and pasted in the sample code from your guide.

Is it an issue on my part or is it an Ammy related issue?

**Comment by ionoy** [comment]
This is definitely an Ammy issue. I will take a look as soon as I get a chance.
Meanwhile, can you, please try using Ammy with PCL project? I'm not sure Ammy was ever meant to work with Shared project configuration.

Thanks!

**Comment by WasserEsser** [comment]
Hi, 

Thanks for the fast response.
I have created a PCL project and the syntax highlighting works now.

However, when trying to compile the sample, I get the compilation error that InitializeComponent( ) is not valid in the current context, that is moving it from App's constructor to MainPage's one.

When trying to compile the project with leaving the InitializeComponent call inside of App's constructor, I get the same compilation error from above, with the difference being that the PCL project itself compiles but the Android project doesn't.

> 2>------ Erstellen gestartet: Projekt: AmmyXamarinPCL.Android, Konfiguration: Debug Any CPU ------
2>    Processing: obj\Debug\res\layout\tabbar.xml
2>    Processing: obj\Debug\res\layout\toolbar.xml
2>    Processing: obj\Debug\res\values\styles.xml
2><Default>(1,1,1,1): error : Ammy compilation error: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
2><Default>(1,1,1,1): error :    bei DotNet.TopConstructedTypeSymbol.EvalProperties(DependentPropertyEvalContext context)
2><Default>(1,1,1,1): error :    bei Ammy.Backend.ReflectionBackend.CreateConstructedTypeSymbol(Type type)
2><Default>(1,1,1,1): error :    bei Ammy.Backend.ReflectionBackend.GetTypeSymbol(Type type)
2><Default>(1,1,1,1): error :    bei Ammy.Backend.ReflectionBackend.InitBaseTypeSet()
2><Default>(1,1,1,1): error :    bei Ammy.Backend.ReflectionBackend.LoadExternalSymbols(IEnumerable`1 libs, String libPath, ICompilerMessages compilerMessages, DependentPropertyEvalContext context)
2><Default>(1,1,1,1): error :    bei Ammy.Language.Start.RefreshReferences(Project project)
2><Default>(1,1,1,1): error :    bei Ammy.Language.Start.RefreshReferences(CancellationToken _cancellationToken, Project project)
2><Default>(1,1,1,1): error :    bei Ammy.Build.AmmyProject.RefreshReferences()
2><Default>(1,1,1,1): error :    bei Ammy.Build.AmmyCompiler.Compile(AmmyProject project, Boolean generateMetaFile, Boolean needBamlGeneration, Boolean needUpdate)
2>c:\users\prakti\documents\visual studio 2017\Projects\AmmyXamarinPCL\packages\Ammy.1.2.74\build\Ammy.targets(16,5): error : Ammy compilation failed

**Comment by ionoy** [comment]
You only need to install Ammy.XamarinForms to a PCL. So try uninstalling it from an Android project.

**Comment by WasserEsser** [comment]
Hi, 

Thanks for another quick reply. 
I'm new to Xamarin and C# in general, sorry for any mistakes on my end.

I have removed Ammy.XamarinForms from the Android and the IOS project while keeping it for the PCL one.

Now I get a different error:

> 1>c:\users\prakti\documents\visual studio 2017\Projects\AmmyXamarinPCL\packages\Ammy.1.2.74\build\internal.cs(4,16,4,28): error CS0246: The type- or namespacename "AmmySidekick" not found (is a using directive or assembly reference missing?)

Where can I find that to reference it in my project?

**Comment by ionoy** [comment]
No problem at all.

It seems that Ammy package is referenced somewhere where Ammy.XamarinForms is not. I would guess that you have uninstalled `Ammy.XamarinForms`, but didn't uninstall `Ammy`.

**Comment by WasserEsser** [comment]
Hi,

Thanks for your response.
You were correct, Ammy was still installed.

Thanks for your help resolving my issue.

**Comment by JohnLouderback** [comment]
@ionoy Does this mean Ammy can't be used at all with a Xamarin shared project? I'm trying to convert my Xamarin shared project to use Ammy, but I'm also getting the `Ammy compilation error: System.NullReferenceException: Object reference not set to an instance of an object.` error.

**Comment by ionoy** [comment]
`NullReferenceException` can mean a lot of things, I'm not sure what it means in your case. Did you install `Ammy.XamarinForms` package? In a Shared project configuration, you should install it into the platform project (Android).

**Comment by JohnLouderback** [comment]
@ionoy  I did. I've noticed that, while it works fine with WPF, with Xamarin Form the syntax highlighting won't work on .ammy files and the files won't build on save either, which leave me with an empty .g.xaml file. I definitely have the extension installed as well.

**Comment by ionoy** [comment]
Can you send me a sample project that I can run on my machine?

Thanks!

**Comment by JohnLouderback** [comment]
@ionoy Sorry for the delay. I was very busy with the holidays. Here is an example which, for me, does not work: https://github.com/JohnLouderback/AmmyFXTest

**Comment by ionoy** [comment]
Hey @JohnLouderback 

Sorry for answering so late. I've looked at the project and found a few issues. 
First of all, I don't see Ammy.XamarinForms package installed in the Android project.
Secondly, it seems, that you've added Page1.ammy manually. Although there is not much difference, you should still add it with the Add New dialog. 
Third, is that this is a Shared project configuration and Ammy wasn't properly tested with one. 

Unfortunately, I can't build this project at all right now. MSBuild gives me this weird error: `error MSB4166: Child node "2" exited prematurely. Shutting down.` I'm not sure how to fix it, and I don't want to reinstall the Visual Studio at the moment.

**Comment by JohnLouderback** [comment]
@ionoy  Does Ammy not work with iOS projects? I believe that's where I installed the Ammy.XamarinForms package
