### ISSUE TITLE
Xamarin Forms ListView doesn't show any items when Ammy's live update feature is enabled

### ISSUE THREAD

**Issue by WasserEsser** [AmmyUI/AmmyUI#102]
Xamarin Forms' ListView doesn't show any items when running with Ammy's live update feature enabled.

This means that we can't use the live update feature of Ammy for pages that make use of ListView, which is a huge downside since we have to compile the project over and over again to see changes made to the UI.

Steps to reproduce:

- Make a brand new Cross Platform Xamarin Forms Application using Visual Studio and select PCL as code sharing strategy
- Add Ammy.XamarinForms from NuGet
- Add a new Ammy Page for Xamarin Forms
- Add a ListView
- Bind data to the ListView 
- Start the application in debug mode

You can either compile in release mode or define NO_AMMY_UPDATE in order to see items in the ListView again.

**Comment by ionoy** [comment]
How do you bind the data?

**Comment by WasserEsser** [comment]
@ionoy I'm binding the data by specifying the item source in my code behind file and using the bind directive in Ammy to bind to specific properties.

**Comment by ionoy** [comment]
That's your problem. Try binding from `.ammy` file. It's easier anyway.

**Comment by WasserEsser** [comment]
I have done that before and this results in the list not showing any elements in both debug and release mode, regardless of Ammy's live update feature being enabled or not.

**Comment by ionoy** [comment]
It seems to me that the binding was wrong then. Can you post your binding code from code behind?

**Comment by WasserEsser** [comment]
All I've done in the code behind file was setting ItemSource by doing `MenuList.ItemSource = MenuItems;`

**Comment by ionoy** [comment]
And where does `MenuItems` come from? Is it defined by a control?

In this case, your binding should look like this:

```
ItemSource: bind MenuItems from $this
```

**Comment by WasserEsser** [comment]
It's an ObservableCollection within my MenuPage.

**Comment by ionoy** [comment]
Well, I'm not sure `RelativeSource={RelativeSource Self}` will work with Xamarin Forms. The easiest workaround should be setting `BindingContext = this` in the constructor. But as I mentioned before, the best practice is to define a separate view model class that holds the data (MenuItems) and then assigning it to `BindingContext`

**Comment by WasserEsser** [comment]
Ammy is generating 
```
<ListView.ItemsSource>
      <Binding Path="MenuItems" RelativeSource="{x:Static RelativeSource.Self}"/>
    </ListView.ItemsSource>
```
when specifying `ItemsSource: bind MenuItems from $this` which results in the following exception being thrown: 
>Xamarin.Forms.Xaml.XamlParseException: Position 4:33. Type RelativeSource not found in xmlns http://xamarin.com/schemas/2014/forms

As this is a quick prototype which will be implemented in multiple different technologies such as Xamarin Forms, Apache Cordova etc. I'd rather like to avoid creating additional ViewModels just for quick data representation.

Setting the binding context inside my code behind file for MenuPage doesn't work either and displays an empty ListView.

**Comment by ionoy** [comment]
It should look like this:

MenuPage.xaml.cs:

`BindingContext = this;`

MenuPage.xaml:

```
ItemSource: bind MenuItems
```

**Comment by WasserEsser** [comment]
I was setting `MenuList.BindingContext = this;` inside MenuPage.ammy.cs while specifying `ItemSource: bind MenuItems` inside MenuPage.ammy, which didn't work.

I also tested what you provided above by specifying the BindingContext of the page itself by only doing `BindingContext = this;` inside MenuPage.ammy, but this didn't work either and still displays an empty ListView.

**Comment by ionoy** [comment]
Hmm, that's weird. Are there any binding diagnostic messages in the Output window? 

Your problem stems from the fact, that you assign `MenuList.ItemSource` in code behind. When page's XAML gets reloaded, all the controls are instantiated again, including `MenuList`. It's not a problem when binding is defined in XAML since it gets applied upon instantiation. But Ammy can't call your code-behind logic again, it doesn't know anything about it.

**Comment by WasserEsser** [comment]
I see, and I was able to fix my issue.

I didn't think about C#'s default class member access level being private, and dumb me wasn't specifying any access level to my property MenuItems.
Specifying ItemSource from within my code behind file didn't need a public access level and thus was fine with it being private.

**Comment by ionoy** [comment]
Yeah, I also forgot about that. I'm glad you fixed the issue.
