### ISSUE TITLE
Name on a Content Page

### ISSUE THREAD

**Issue by claudioluciano** [AmmyUI/AmmyUI#103]
Hey how do i set a name on a content page like on xaml  (x:Name="root")?

**Comment by ionoy** [comment]
`x:Name` syntax should work like this:

```
ContentPage "root" {
  ...
}
```

**Comment by claudioluciano** [comment]
Nope, not on ContentPage, the first string after the type is (x:Class), on other components like button “Button “myButton” {
}
Works fine..

**Comment by ionoy** [comment]
In this case, you can use typeless properties: 
```
  "x:Name": "root"
```
