### ISSUE TITLE
Example of usage design-time attributes (xmlns:d namespace)

### ISSUE THREAD

**Issue by meancrazy** [AmmyUI/AmmyUI#114]
How can I do something like this
```csharp
xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
xmlns:vm="ViewModels"
mc:Ignorable="d"
d:DataContext="{d:DesignInstance {x:Type vm:MainViewModel}, d:IsDesignTimeCreatable=False}"
```
in AmmyUI?

So I think that this can be related with #14.

**Comment by ionoy** [comment]
Hello @meancrazy 

You can use typeless properties for that:
```
"xmlns:d": "http://schemas.microsoft.com/expression/blend/2008"
"xmlns:mc": "http://schemas.openxmlformats.org/markup-compatibility/2006"
...
```

These will be directly translated into the XAML.

**Comment by meancrazy** [comment]
Typed bindings and code autocompletition doesn't works with typeless props :(

**Comment by ionoy** [comment]
Yep. But you shouldn't use typeless properties too often. It's basically a hack to get whatever XAML you want.

**Comment by meancrazy** [comment]
So what should I write in ammy to get autocompletition for bindings to VM in ammy?

**Comment by ionoy** [comment]
Unfortunately, bindings are not type-checked at the moment. So you won't have any autocompletion.

**Comment by meancrazy** [comment]
Thanks! Any plans to realize this?

**Comment by ionoy** [comment]
There is a `viewmodel MyViewModelType` syntax, but it caused too much complexity for binding semantic analysis, so I decided to cut it off for the time. Not sure whether I will add it in the future or not.

**Comment by meancrazy** [comment]
Thank you
