### ISSUE TITLE
Cant build Ammy.Syntax

### ISSUE THREAD

**Issue by adinhalilovic** [AmmyUI/AmmyUI#119]
When i tried to build Ammy.Syntax project i got an error :
Nemerle.MSBuild.targets(289,5): error : internal compiler error: got some unknown exception of type System.MissingMethodException: Method not found: 'Nemerle.Collections.ListEnumerator`1<!0> Nemerle.Core.list`1.GetEnumerator()'

How to fix this ?

**Comment by ionoy** [comment]
Hello @adinhalilovic 

Thanks for the feedback and sorry for taking it so long to respond.

You can fix it by installing `v1.2.543.0` version of Nemerle from here http://nemerle.org/BuildHistory?major=1&minor=2

Make sure to uninstall the old version first and close the Visual Studio.
