### ISSUE TITLE
can't use namespace in bind

### ISSUE THREAD

**Issue by Developerius** [AmmyUI/AmmyUI#120]
Sample bind AttachedProperty
requered XAML
`<Binding Path="(namespace:PropertiesList.Label)">`

**Comment by ionoy** [comment]
I think you can do something like this:

```
"xmlns:namespace": "..."
Text: Binding {
  Path: "namespace:PropertiesList.Label"
}
```

**Comment by Developerius** [comment]
thank you! that works.
