### ISSUE TITLE
Slow file operations because of ammy.targets

### ISSUE THREAD

**Issue by jurij** [AmmyUI/AmmyUI#138]
One of my projects has about 100 *.ammy files each 100-200 LOC.
When I try to add, rename or delete any files in VS 2017, Visual Studio freezes for about 10 seconds. When I remove `Ammy.target` from the .csproj, my Issue is gone.

Line in .csproj: `<Import Project="..\..\packages\Ammy.1.2.94\build\Ammy.targets" Condition="Exists('..\..\packages\Ammy.1.2.94\build\Ammy.targets')" />`

My question: Should the ammy compiler handle 100 files, each about 100-200 LOC easily?
Does someone else experience Issues like that?

**Comment by ionoy** [comment]
Hello @jurij 

I'm not sure how to mitigate this issue properly. What is actually happening, is Visual Studio running background build when you modify the project. I have already tried to do something about that here: https://github.com/AmmyUI/AmmyUI/blob/master/src/Core/Ammy.Build/AmmyCompilerTask.cs#L63

This was tested on VS2015 though, so a lot of stuff might have changed. Can you build Ammy on your machine? Then you could uncomment `Debugger.Launch()` and see if there is a stack trace that you could filter out. Or there might be a better way.

**Comment by jurij** [comment]
Thank you for replying so quickly, I will try to debug.
I am using VS 2017 Enterprise and have installed Nemerle and https://github.com/JetBrains/Nitra. 
Still all .nproj Projects in Ammy.sln are incompatible.
Is there something I am missing? Any more Plugins?

**Comment by jurij** [comment]
I got Nemerle to work on my machine.
Every project compiles except `Ammy.Syntax`

Which version of Nemerle are you using? 
I have installed `NemerleSetup-net-4.0-v1.2.547.0`

Error: 
```
"C:\dev\AmmyUI\Ammy.sln" (default target) (1) -> 
"C:\dev\AmmyUI\src\Core\Ammy.Syntax\Ammy.Syntax.nproj" (default target) (3) -> (CoreCompile target) -> 
C:\Program Files (x86)\Nemerle\Net-4.0\Nemerle.MSBuild.targets(289,5): error : 
internal compiler error: got some unknown exception of type System.TypeLoadException: 
Could not load type 'Nemerle.Collections.ListEnumerator`1' 
from assembly 'Nitra.Grammar, Version=0.1.4015.0, Culture=neutral, PublicKeyToken=e080a9c724e2bfcd' due to value type mismatch. 
[C:\dev\AmmyUI\src\Core\Ammy.Syntax\Ammy.Syntax.nproj]
```
