### ISSUE TITLE
Wrong attached DependencyProperty

### ISSUE THREAD

**Issue by draco1023** [AmmyUI/AmmyUI#15]
![image](https://cloud.githubusercontent.com/assets/1821583/22181453/dfde777a-e0c7-11e6-9ebd-b4d8a23303ee.png)

Namespace is missing in the generated .g.xaml file

![image](https://cloud.githubusercontent.com/assets/1821583/22181457/067e14c6-e0c8-11e6-811c-55ed699028c7.png)

By the way, it'll be perfect if the Path "." can be omitted to bind to DataContext directly.

**Comment by ionoy** [comment]
Missing namespace is definitely a bug. Ammy doesn't resolve it for Attached Properties at the moment. I will fix it in a moment and upload it to MyGet feed.

Nuget V3: https://www.myget.org/F/ammy/api/v3/index.json
Nuget V2: https://www.myget.org/F/ammy/api/v2

As for binding you can just write:

    DialogParticipation.Register: bind
    Height: 960

**Comment by ionoy** [comment]
Alright, new version is uploaded to MyGet, you can test it now. 

Thanks for report!

**Comment by draco1023** [comment]
You are right, "bind" is just OK. And thanks for fix it!
