### ISSUE TITLE
www.ammyui.com - domain expired - documentation?

### ISSUE THREAD

**Issue by matejkac** [AmmyUI/AmmyUI#152]
www.ammyui.com domain expired.
Where can we get the complete documentation?

**Comment by ionoy** [comment]
Sorry, I didn't realize people were still using AmmyUI. Domain is restored now.

**Comment by matejkac** [comment]
Thanks for the fast response.
Working on an upgrade of an older application, so I need the docs.
I like working with AmmyUI, it's a lot less verbose than XAML.

Closing as completed.
