### ISSUE TITLE
.ammy file reformat + formatting options

### ISSUE THREAD

**Issue by aienabled** [AmmyUI/AmmyUI#25]
Hi!

I very needed the document reformat feature as having to manually format thousands of lines of code is no way timesaving than having XAML with ReSharper (where I can select the project root and ask it to reformat/cleanup all the files in the project).

Also I would like to have a formatting options for brackets style - some people absolutely cannot live with "Egyptian" K&R style brackets.

Regards!

**Comment by ionoy** [comment]
Reformatting shouldn't be to difficult to implement. Although there is not Options window for Ammy at the moment so I would have to create one.

**Comment by ionoy** [comment]
Done! Updated NuGet package + Extension will be published by the end of the week.
