### ISSUE TITLE
Use alias parameter to set a static resource

### ISSUE THREAD

**Issue by lucamnn** [AmmyUI/AmmyUI#26]
We'are trying to write an alias like this:

`alias AppIcon(id, size) {
  ContentControl {
    Style: resource $id
    Width: $size
	Height: $size
  }
}`

It seems that is not possible, because the $id parameter is unexpected.

Is there any way to achieve such result?

**Comment by ionoy** [comment]
You should be able to do something like this:

```
alias AppIcon(id, size) {
  ContentControl {
    Style: StaticResourceExtension {
      ResourceKey: $id
    }
    ...
  }
}
```

BTW, you can post questions on StackOverflow with tag "ammy", I'm following it.

Thanks!

**Comment by lucamnn** [comment]
Thanks for your support. Next time i will use StackOverflow for questions like this.
