### ISSUE TITLE
Invalid TargetType in Style

### ISSUE THREAD

**Issue by isukces** [AmmyUI/AmmyUI#27]
Following code
```Style { TargetType: "Telerik.Windows.Controls.RadComboBox", #Setter("Margin", "0,3,0,3")}```
is converted into 
```
<Style TargetType="Telerik.Windows.Controls.RadComboBox">
  <Setter Property="Margin" Value="0,3,0,3"/>
</Style>
```

**Comment by ionoy** [comment]
Yeah, with types you either use XAML syntax, as in `{x:Type TextBlock}` or omit quotes:

```
TargetType: Telerik.Windows.Controls.RadComboBox
```

**Comment by isukces** [comment]
Thank you. It works.
