### ISSUE TITLE
ValidationRules as static resource

### ISSUE THREAD

**Issue by isukces** [AmmyUI/AmmyUI#28]
Ammy converts ValidationRules from following code
```
@MyTextBox("3") {
    Text: bind CustomHeight
    set [
        ValidationRules: [ 
            resource  "HeightDoubleValidation"
        ]
    ]            
}
```
into
```
<Binding.ValidationRules>
{StaticResource HeightDoubleValidation}
</Binding.ValidationRules>
```
but probably should convert into something like this
```
<Binding.ValidationRules>
 <StaticResource ResourceKey="HeightDoubleValidation"/>
</Binding.ValidationRules>
```

**Comment by ionoy** [comment]
Yeah, we should detect if resource is used inside array and generate node syntax. 
Meanwhile you can write:

```
ValidationRules: [
  StaticResourceExtension {
    ResourceKey: "HeightDoubleValidation"
  }
]
```

Which is a good candidate for a mixin.

Thanks for submitting an issue!

**Comment by isukces** [comment]
I suppose that mixin should be something like this
```
mixin AddStaticValidationRule(key) for Binding {
	combine ValidationRules:  StaticResourceExtension {
		ResourceKey: $key
	}
}
```
but I don't know how to properly use it. Following code gives neither xaml effect nor compile error.
```
SelectedValue: bind MyData.Username from "TopWindow"
set [
	#AddStaticValidationRule("HeightDoubleValidation")
]
```
The result is 
```
<Binding Path="MyData.Username" ElementName="TopWindow"/>
```

By the way. I think there is another good candidate for mixin
```
mixin MergedDictionary (source) for ResourceDictionary {
  combine MergedDictionaries: ResourceDictionary { Source: $source }
}
```

**Comment by ionoy** [comment]
Great idea with `MergeDictionary`!

Seems like mixins have problems within `set []`. I'll see about it today.

**Comment by ionoy** [comment]
This was fixed in the latest version, please update. 

Thanks for submitting this issue!

**Comment by isukces** [comment]
Great. It works.
