### ISSUE TITLE
Moving .ammy-file keeps .g.xaml file

### ISSUE THREAD

**Issue by aienabled** [AmmyUI/AmmyUI#29]
Hi,

When I move any `.ammy` file a corresponding `.g.xaml` file is still kept.
I think the best solution is to detect cases when there is a `.g.xaml` without a corresponding `.ammy` file and simply remove them.
Also plugin for VS could listen to file rename/move events and rename/move the corresponding `.g.xaml` file as well.

Regards!

**Comment by distantcam** [comment]
I was going to open a different issue for this, but this issue is similar.

Can the `.g.xaml` files be generated in the intermediate `obj` directory instead of the source directory? That way they don't show up in source control as files I need to add or ignore, and the build system will delete them every time there's a new build, solving the problem of cleaning them up when the `.ammy` file is renamed.

**Comment by ionoy** [comment]
Initially, it was the idea. But unfortunately, I couldn't make it work with WPF. XAML subsystem depends on file paths to generate proper resources and resource names. I don't remember the exact issue, but there was a problem with generated `InitializeComponent` when .xaml files were put in `obj` directory. Maybe there is a solution for this, but I couldn't find it at the moment.

Actually, .g.xaml suffix was added with the idea of .gitignore in mind.

**Comment by distantcam** [comment]
> XAML subsystem depends on file paths to generate proper resources and resource names.

Ohhh yeah I remember now. Pack paths are relative to the directory the `.xaml` file is in. Poop. I struggled against that too and never found a good solution.

**Comment by matkoch** [comment]
Isn't it possible to add the g.xaml files as dependent files too? Like the ammy.cs ones... I did this manually so far, because ReSharper will complain about missing methods otherwise. Plus it's still nice being able to navigate to the generated code.

**Comment by ionoy** [comment]
I like this idea. You can actually use a built-in XAML designer preview with this approach. But unfortunately, it doesn't solve moved file problem. Seems like I will have to track move/rename event from VS Extension and rename dependent files. Same goes for deletion.

**Comment by matkoch** [comment]
@ionoy I added this part manually:


    <ItemGroup>
      <None Include="Chapter\ChapterWindow.g.xaml">
        <DependentUpon>ChapterWindow.ammy</DependentUpon>
        <SubType>Designer</SubType>
      </None>
    </ItemGroup>

And it actually _does_ move the generated file... No left-overs.

**Comment by ionoy** [comment]
Maybe I'm missing something. Could you post a sample project?

**Comment by matkoch** [comment]
Just check out my LiveDemoRecords project.

**Comment by ionoy** [comment]
Got it. Seems like it works when you are actually moving a file, but doesn't if you rename it. Which is kinda logical, I guess.

**Comment by matkoch** [comment]
Okay I didn't test _rename_ :) But I guess having support for _move_ and _delete_ is pretty descent already.

**Comment by ionoy** [comment]
Agreed.

**Comment by ionoy** [comment]
`g.xaml` file is included in a project @matkoch suggested. You will need to update VS extension and `Add -> New item...`. No automatic upgrade, sorry :)
