### ISSUE TITLE
ResourceDictionary file template, also MergedDictionaries support

### ISSUE THREAD

**Issue by aienabled** [AmmyUI/AmmyUI#30]
Hi,

Currently there are no VS file template for `ResourceDictionary`.

Also Ammy doesn't allow to compile this code (file example):
```
ResourceDictionary  {
    MergedDictionaries [    
        ResourceDictionary { Source: "Styles/RequiredStyles.ammy" }
        ResourceDictionary { Source:  "Styles/DefaultStyles.ammy" }
    ]
}
```

because "Top node should have a name i.e. UserControl "MyControl"" but that's incorrect as resource dictionary should not have the name (so no `x:Class` attribute is generated in XAML for the root `ResourceDictionary` element).

Another issue is that we need a rewriting of Source elements - `Styles/RequiredStyles.ammy` should become `Styles/RequiredStyles.g.xaml` in the resulting XAML.

Ideally, we also want a mixin so we could write
```
ResourceDictionary {
   #Merge("Styles/RequiredStyles.ammy")
   #Merge("Styles/DefaultStyles.ammy")
}
```
and it should be available only in ResourceDictionary element and combine these `#Merge` into the MergedDictionaries elements.

Regards!

**Comment by ionoy** [comment]
`ResourceDictionary` support was added in the latest version. You will have to update visual studio extension for "Resource Dictionary" item template.
