### ISSUE TITLE
System.Windows.Interactivity support?

### ISSUE THREAD

**Issue by jstaro** [AmmyUI/AmmyUI#31]
Having trouble getting `System.Windows.Interactivity.EventTrigger` to work.

This is how the old XAML I want to convert looks like:
```xml
<Window x:Class="SomeApp.MainWindow"
    xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
    [...]>
    
    <TextBox Text="{Binding [...]}">
        <i:Interaction.Triggers>
            <i:EventTrigger EventName="TextChanged">
                <i:InvokeCommandAction
                    Command="{Binding [...]}"
                    CommandParameter="{Binding [...]}" />
            </i:EventTrigger>
        </i:Interaction.Triggers>
    </TextBox>
</Window>
```
I've tried both by importing the `System.Windows.Interactivity` namespace, and using fully qualified names, but Ammy doesn't like anything in this namespace.

**Comment by ionoy** [comment]
Hello jstaro,

This issue have been resolved 3 days ago, although I'm not sure if it made it to NuGet already. If not, you can try MyGet feed as specified in this thread:

https://github.com/AmmyUI/AmmyUI/issues/14

**Comment by jstaro** [comment]
Yes, I updated to 1.1.25 and it works. Thank you again.
