### ISSUE TITLE
"Inline" Runs and whitespace inside TextBlocks

### ISSUE THREAD

**Issue by jstaro** [AmmyUI/AmmyUI#32]
There's a way in old, ugly XAML to databind Runs inside Textblocks without creating whitespace inbetween:
```xml
<TextBlock>
    <Run>some label text: </Run><Run Text="{Binding Text1}" />(<Run Text="{Binding Text2}" /> trailing)
</TextBlock>
```
produces the following text:
`some label text: {Text1}({Text2} trailing)`

However, since Ammy works as it does, and doesn't collapse whitespace (for understandable reasons) as SGML-like languages do, I can't really see a way to get the same behaviour by just using Ammy.
The closest analogue I can come up with in new, pretty Ammy:
```
TextBlock {
  Run { "some label text:" }
  Run { Text: bind Text1 }
  Span { "(" }
  Run { Text: bind Text2 }
  Span { " trailing)" }
}
```
produces the following text:
```
label text: {Text1} ( {Text2} trailing)
                   ^ ^
```

Unless I'm missing something, I guess the solution is to make a new computed viewmodel property for this text?

**Comment by aienabled** [comment]
+1,
and I really would love to see something like C# string interpolation for that (very popular) case! Something like this:
```
TextBlock { $"foofoo: {bind Text1} foo {bind Text2}" }
```

**Comment by jstaro** [comment]
That is a brilliant idea!

**Comment by aienabled** [comment]
Yes :-).
Also what you're looking for is seems to be already possible with the binding converter:
```
TextBlock { Text: bind
                          convert (ViewModelTypeName vm) => "foofoo: " + vm.Text1 + " foo " + vm.Text2
```

**Comment by ionoy** [comment]
I this binding converters are a way to go here. But we could also think about implementing some specific workaround for `TextBlock`.

**Comment by jstaro** [comment]
@aienabled Oh, I had no idea about the `convert` syntax. That's super handy. Thank you both!
