### ISSUE TITLE
how to set FieldModifier ?

### ISSUE THREAD

**Issue by isukces** [AmmyUI/AmmyUI#34]
What is the proper syntax for FieldModifier? I want to get following XAML.
```
<PasswordBox x:Name="EdPassword"  x:FieldModifier="private" />
```
I've checked this.
```
PasswordBox "EdPassword" { FieldModifier: "private" }
```
but it doesn't work.

**Comment by ionoy** [comment]
You can use typeless property syntax:

PasswordBox "EdPassword" { 
  "x:FieldModifier": "private" 
}

I will add documentation shortly.

You will have to update to latest version, though.
