### ISSUE TITLE
ResourceDictionary definition in Ammy

### ISSUE THREAD

**Issue by isukces** [AmmyUI/AmmyUI#35]
There is possibility to define with Ammy Window, Application and User control but I don't found how to define ResourceDictionary as a separate file. 
It would be great to have top level syntax like 
```
ResurceDictionary {
}
```
that produces xaml resource file that can be used in old fashioned XAML.

**Comment by ionoy** [comment]
Yeah, that was already mentioned by people. I'll try to add it as soon as possible.

**Comment by ionoy** [comment]
`ResourceDictionary` support was added in the latest version. You will have to update visual studio extension for "Resource Dictionary" item template.
