### ISSUE TITLE
Adding a node without {} doesn't cause an error, and doesn't compile to what I expected.

### ISSUE THREAD

**Issue by distantcam** [AmmyUI/AmmyUI#40]
So I went through the quickstart, and when adding the `Host` to the `MainWindow` I wrote the following.

    Window "AmmyQuickstart.MainWindow" {
        AmmyQuickstart.Host
    }

The problem is this compiled, but didn't actually add the `Host` to the `MainWindow.g.xaml`. It also didn't cause a compiler error.

Is this valid Ammy code?

**Comment by ionoy** [comment]
Hello @distantcam,

`AmmyQuickstart.Host` is indeed invalid Ammy code. It is actually parsed as an `IncompleteProperty` AST node. 

I have added appropriate error message that would point that out. It will be included in the next NuGet release. I'm currently working on proper Xamarin.Forms support, so it will take few more days.

Thanks for submitting an issue!
