### ISSUE TITLE
VS2017 extension support

### ISSUE THREAD

**Issue by aienabled** [AmmyUI/AmmyUI#42]
VS2017 release is coming very soon and we've already migrated to VS2017 RC. Works just great on our quite big solutions, no problems so far. Performance is also on par with VS2015.

**Comment by ionoy** [comment]
Shouldn't be a problem apart from my cramped SSD that doesn't have enough free space to install VS2017. I'll roll out VS2017 support, as soon as it's dealt with.

**Comment by aienabled** [comment]
By the way, VS2017 has a new installer so if you choose only .NET desktop support and VS SDK it will take just 5GB.

**Comment by ionoy** [comment]
Thanks for the info, I'll take a look.

**Comment by Mike-EEE** [comment]
Yeah that is good to know, @aienabled.  I am looking forward to the [March 7th release](https://blogs.msdn.microsoft.com/visualstudio/2017/02/09/visual-studio-2017-launch-event-and-20th-anniversary).  I use a ton of extensions, however, so it will be a while before I can enjoy what I have now in VS2015 (it's soooooo nice!).

**Comment by ionoy** [comment]
I've uploaded new versions of NuGet package and Visual Studio Extension. New extension support VS2017 now.

Keep in mind, that since Ammy is now actually multiplatform you will have to `install-package Ammy.WPF` or `install-package Ammy.XamarinForms`
