### ISSUE TITLE
Support Xamarin XAML

### ISSUE THREAD

**Issue by cdie** [AmmyUI/AmmyUI#5]
It would be really awesome, if, from one Ammy code, we could generate XAML for WPF, UWP and Xamarin. 
I had once a project like that to create "standard XAML" that compile on every platform. It would make more generic UI development.

**Comment by ionoy** [comment]
This is definitely an interesting idea. Although, as with any multiplatform framework, we would have to create a subset of original frameworks, basically an intersection of all. Another way is to define own "framework" that would be translated into each specific platform. Are you talking about the latter?

**Comment by cdie** [comment]
Yes, that was my original idea, few years ago.
But instead of "reinventing" a whole new framework/language, I was thinking about using HTML/CSS to compile into XAML, like that I could target both XAML apps and web. However, I was always missing time to do such project... 
What I think is you should create your own framework, based on WPF (I think it's the most complete and the best starting point) to define it

**Comment by ionoy** [comment]
Will get back to this idea as soon as soon as I clear high priority tasks with Ammy. Thanks for the suggestion!

**Comment by ionoy** [comment]
Ammy supports Xamarin Forms now. You need to `install-package Ammy.XamarinForms`.

More information here http://www.ammyui.com/documentation/xamarin-forms-quickstart/
