### ISSUE TITLE
The tag '...' does not exist in XML namespace

### ISSUE THREAD

**Issue by olegtarasov** [AmmyUI/AmmyUI#51]
When I create an Ammy user control and then use it in another control, the editor gives me an error: The tag '[custom control]' does not exist in XML namespace '[namespace]'. Both controls are in the same namespace and I include a `using [namespace];' directive inside the parent control. This warning also appears during build process, but the project builds and works as expected.

Here is the code:

Mixins.ammy:
```
alias LabeledControl(caption) {
	StackPanel {
		Orientation: Horizontal

		Label { 
			Margin: 4
			Content: $caption
		}		
	}
}

alias LabeledText(caption, binding)
{
	@LabeledControl($caption) {
		TextBlock { 
			#VCenter

			Margin: 4
			Text: $binding
		}
	}
}

alias LabeledTextBox(caption, binding, width=40) {
	@LabeledControl($caption) {
		TextBox { 
			#VCenter

			Margin: 4
			Width: $width
			Text: $binding
		}
	}
}

alias PaddedButton(text) {
	Button { 
		Margin: 4
		Padding: "8 2"
		Content: $text
	}
}

mixin VCenter() for FrameworkElement {
	VerticalAlignment: Center
}
```

TrainOptionsControl.ammy:
```
UserControl "Retia.Gui.Windows.TrainOptionsControl" {
	StackPanel { 
		Orientation: Vertical

		GroupBox { 
			Margin: 4
			Header: "Train options"

			StackPanel { 
				Orientation: Vertical

				@LabeledTextBox("Error filter:", bind ErrorFilterSize) {}
				@LabeledTextBox("Max epoch:", bind MaxEpoch) {}
				@LabeledTextBox("Learning rate:", bind LearningRate) {}
				@LabeledTextBox("LR scale factor:", bind LearningRateScaleFactor) {}
				@LabeledTextBox("LR scale period:", bind LearningRateScalePeriod) {}

				@PaddedButton("Apply") {
					HorizontalAlignment: Left
					Command: bind ApplyOptionsCommand
				}
			}
		}

		StackPanel { 
			Orientation: Horizontal

			@PaddedButton("Start / Resume") {
				Command: bind StartResumeCommand
			}
			@PaddedButton("Pause") {
				Command: bind PauseCommand
			}
		}
	}
}
```

TrainingControl.ammy:
```
using Retia.Gui.Windows;

UserControl "Retia.Gui.Windows.TrainingControl" {
	Grid { 
		ColumnDefinitions: [
			ColumnDefinition {Width: Auto}
			ColumnDefinition {Width: "*"}
		]

		Expander { 
			Grid.Column: 0
			ExpandDirection: Right
			IsExpanded: true
			UseLayoutRounding: true

			Header: TextBlock { 
				Text: "Settings" 
				LayoutTransform: RotateTransform {Angle: -90}
			}

			ScrollViewer { 
				VerticalScrollBarVisibility: Auto
				HorizontalScrollBarVisibility: Disabled
				MaxWidth: 300

				StackPanel { 
					Orientation: Vertical

					TrainOptionsControl { DataContext: bind OptionsModel }
				}
			}
		}

		TrainingReportControl { 
			Grid.Column: 1
			DataContext: bind ReportModel
		}
	}
}
```

You can find the whole project in my repo: https://github.com/total-world-domination/Retia. Open Retia.CPUOnly.sln to build without external dependencies.

**Comment by ionoy** [comment]
Thanks, I'll take a look

**Comment by ionoy** [comment]
Fixed. WPF's markup compiler task was given incorrect assembly path, assuming it was `.exe`. In your case it's `.dll`

I've uploaded a new version of Ammy to MyGet. Please check if it fixes you problem.

Nuget V3: https://www.myget.org/F/ammy/api/v3/index.json
Nuget V2: https://www.myget.org/F/ammy/api/v2

Add it to Options -> NuGet Package Manager -> Package Sources
Don't forget to click Update button there.

After that just switch Package Manager source to this new feed and update-package Ammy. You might need to restart Visual Studio since it uses assemblies from a package.

---- 

By the way, Retia seems like a cool project! It's a shame I don't know much about deep learning.

Anyway, thanks for submitting an issue!

**Comment by ionoy** [comment]
Oh, almost forgot.

You will have to use `Ammy.WPF` package now since Ammy is now multiplatform. It will reference `Ammy` package as a dependency.

**Comment by olegtarasov** [comment]
Yes, that fixed it. Thank you very much for such a quick reply!

**Comment by olegtarasov** [comment]
Actually I've just noticed that build warnings are still there:

```
8>C:\Projects\Hannibal\Retia\packages\Ammy.1.2.10\build\Ammy.targets(10,5): warning : C:\Projects\Hannibal\Retia\Retia.Gui\Windows\TrainingControl.ammy(26,5,30,6): The tag 'TrainOptionsControl' does not exist in XML namespace 'clr-namespace:Retia.Gui.Windows'. 
8>C:\Projects\Hannibal\Retia\packages\Ammy.1.2.10\build\Ammy.targets(10,5): warning : C:\Projects\Hannibal\Retia\Retia.Gui\Windows\TrainingWindow.ammy(7,2,7,39): The tag 'TrainingControl' does not exist in XML namespace 'clr-namespace:Retia.Gui.Windows'. 
```

**Comment by ionoy** [comment]
Compilation may show these warnings on initial compilation since there is no compiled assembly yet at TargetPath. After initial compilation, it shouldn't show any warnings. Is it the same situation with you?

**Comment by olegtarasov** [comment]
As a matter of fact, yes, warnings disappear on consecutive builds and reappear only on Rebuild. Since everything works fine, I don't think it's much of a problem :)
