### ISSUE TITLE
Create ResourceDictionary with Ammy

### ISSUE THREAD

**Issue by chrischu** [AmmyUI/AmmyUI#52]
As far as I know currently it is only possible to create UserControls, Windows, App and Mixin files. It would be really awesome if it was possible to create ResourceDictionaries with Ammy as well.

**Comment by ionoy** [comment]
It should be possible, afaik. Resource Dictionary item template was added on one of the latest VS Extension releases. Also, make sure you are using latest Ammy version. Note, that you need to install either `Ammy.WPF` or `Ammy.XamarinForms` now to get full installation.

**Comment by chrischu** [comment]
Oh ok. For some reason VS thought the new version of Ammy was a completely different extension and therefore it didn't show me any updates.

**Comment by ionoy** [comment]
I don't think that extension ID has changed. I've added support for VS2017, maybe that was a problem.
