### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by chrischu** [AmmyUI/AmmyUI#54]
Hi!

First of all let me say that I think it's really cool that AmmyUI bugs are fixed quickly and that there seems to be a lot of active development going on!

However, I think it would be great if you could actually provide a little changelog for every new version. This way consumers of Ammy could actually judge if updating might break something (I don't think that has happened yet, but in my experience it is only a matter of time before breaking changes become necessary if you don't want to hamper development speed severely).

http://keepachangelog.com/en/0.3.0/ has some good details on what a changelog should contain :).

**Comment by aienabled** [comment]
Agreed. There was a breaking change recently - when Ammy nuget package was split on multiple (per-platform) nuget packages. There was no way to learn about possible breaking changes.

**Comment by ionoy** [comment]
Great idea! I actually thought about it but wasn't sure if anyone would be interested at this point in time. What would you propose as a location for it? How about AmmyUI/AmmyUI main README.md, so it would be visible on repository front page?

**Comment by chrischu** [comment]
Mhh that would be a great start, but why not also put it on the webpage (e.g. http://www.ammyui.com/changelog)?

**Comment by ionoy** [comment]
Problem is, will it be visible enough? Previously it was possible to open URL on package installation, seems like with `install.ps1` removal it was made impossible.

**Comment by aienabled** [comment]
It will be useful to read changelog before updating with nuget. So I agree with @chrischu.

**Comment by chrischu** [comment]
Yeah especially since the NuGet package project site points to ammyui.com I think it makes sense to publish it there (but there's definitely no harm in ALSO publishing it on the github page).

**Comment by ionoy** [comment]
Changelog is now displayed on NuGet installation
Also, it can be found at http://www.ammyui.com/release-notes.txt

It doesn't look pretty, but I think it will serve its' purpose for the time.
