### ISSUE TITLE
Noesis v2.0

### ISSUE THREAD

**Issue by Mike-EEE** [AmmyUI/AmmyUI#56]
FWIW, [Noesis 2.0 was released](http://www.noesisengine.com/) and it looks amazing.

Unfortunately it also breaks a link on your web page.  Not sure if this is the right place, but thought I would mention. :)

**Comment by aienabled** [comment]
BTW, have you tried it with https://github.com/aienabled/NoesisGUI.AmmyIntegration ?
I don't have time right now to check it. I also planned to update https://github.com/aienabled/NoesisGUI.MonoGameWrapper soon for 2.0 (we have a lot of missing features implemented in our version but still not exported there).

**Comment by Mike-EEE** [comment]
I have not, but I am watching this on the sidelines for now. :)

I have to say that I am not too impressed with Unity when it comes to the .NET look and feel for things.  I might actually be going the MonoGame route, so that is good to know you have magic around there, too. 👍

**Comment by ionoy** [comment]
Fixed the link, thanks!

**Comment by ionoy** [comment]
BTW, Mike, you can join Ammy Gitter if you have any questions or suggestions.

https://gitter.im/AmmyUI/Ammy

**Comment by Mike-EEE** [comment]
Great, will do, @ionoy!

**Comment by aienabled** [comment]
Updated https://github.com/aienabled/NoesisGUI.AmmyIntegration to support NoesisGUI v2.0 and latest Ammy version.
@ionoy please update your fork.
