### ISSUE TITLE
Extention for VS 2017 broken?

### ISSUE THREAD

**Issue by byme8** [AmmyUI/AmmyUI#58]
I installed extension for VS 2017 and during build appeared next error:
`The "Ammy.Build.AmmyCompilerTask" task could not be loaded from the assembly
F:\Develop\C#\WpfApp1\packages\Ammy.1.2.18\build\Ammy.Build.dll. Could not load file or
assembly 'System.Collections.Immutable, Version=1.1.37.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are
available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
`
I added System.Collections.Immutable, but it didn't help.

**Comment by ionoy** [comment]
I will be able to test it tomorrow. Do you have VS2015 installed? Does Ammy work there?

**Comment by byme8** [comment]
I don't have VS 2015 to test it.

**Comment by ionoy** [comment]
"Works on my machine..."

Can you send your project configuration, preferably .csproj file or whole project zipped?

**Comment by byme8** [comment]
[Here](https://github.com/byme8/AmmyTest) you can find the repository and I attached archive with project including the packages directory.
[AmmyTest.zip](https://github.com/AmmyUI/AmmyUI/files/820590/AmmyTest.zip)

**Comment by ionoy** [comment]
Can you try restarting reloading project or better yet restarting Visual Studio? This is a weird issue, first time I tried opening you project I got "cannot load Ammy.VisualStudio.Service.dll" exception. But whatever I tried doing after that, it always worked for me, even if I open a clean version of your project. Sometimes I had to close/open *.ammy file, but this is a different issue.

**Comment by byme8** [comment]
I am tried to create WPF, UWP and Xamarin Forms projects and all of them have the issue. I even tried to reinstall Visual Studio, but it didn't help=)

**Comment by ionoy** [comment]
What is your Windows version/bitness?

Do you have  Nemerle/Nitra installed?

**Comment by byme8** [comment]
I have Windows 10/x64, 1607, OS Build 14393.693. Nemerle/Nitra is missing.

**Comment by ionoy** [comment]
Nothing out of ordinary... Ammy extension version is 1.0.19?

**Comment by byme8** [comment]
Yes

**Comment by ionoy** [comment]
Please, try updating from MyGet:

NuGet V3: https://www.myget.org/F/ammy/api/v3/index.json
NuGet V2: https://www.myget.org/F/ammy/api/v2

Add it to Options -> NuGet Package Manager -> Package Sources
Don't forget to click Update button there.

After that just switch Package Manager source to this new feed and `update-package Ammy.WPF`. You might need to restart Visual Studio since it uses assemblies from a package.

Thanks!

**Comment by aienabled** [comment]
To help investigate the issue, it's a good idea to get the full MSBuild dump. Simply run on that project
```
MSBuild /pp:pp.txt
```
and upload the pp.txt file from that project folder.

**Comment by byme8** [comment]
Build succeeded. The issue is gone.

**Comment by ionoy** [comment]
Glad to hear. Thanks for your patience!
