### ISSUE TITLE
Xamarin runtime update. 

### ISSUE THREAD

**Issue by percramer** [AmmyUI/AmmyUI#59]
Hi,

would it in theorie be possible to download a form layout from a remote server and apply that during runtime? 

Currently i have got a webservice running that just holds basic control positions etc. During runtime this info is downloaded and the applied to the actual controls. But this is a bit limited. If i could upgrade this somehow to AmmyUI that would be a major step forward in this app.

Regards,

Per

**Comment by ionoy** [comment]
Yes, it's possible! But it would require custom solution since Ammy was designed for localhost development.
