### ISSUE TITLE
AmmyUI seems to break DialogHost

### ISSUE THREAD

**Issue by chrischu** [AmmyUI/AmmyUI#62]
I am using AmmyUI together with the MaterialDesign XAML Toolkit (https://github.com/ButchersBoy/MaterialDesignInXamlToolkit) and just stumbled upon a bug that seems to be related to Ammy.

Attached is a solution to reproduce the problem. When I show a dialog with a normal WPF user control everything works fine, however when I use a user control coming from a Ammy file the dialog stops working (the first time it's fine, but the second time it does not show up anymore).

I know this is kinda tricky since it involves two projects, but since the DialogHost works fine with regular WPF user controls, I think the bug lie with Ammy rather than the MaterialDesign XAML Toolkit.
[DialogHostBug.zip](https://github.com/AmmyUI/AmmyUI/files/853342/DialogHostBug.zip)

By the way: I figured the problem might lie in Ammy's auto-update feature but it seems to persist even when adding the "NO_AMMY_UPDATE" compilation symbol.

**Comment by chrischu** [comment]
Did some more investigating: It works as expected when I only instantiate the Ammy user control once (e.g. by storing the instance in the MainWindow). This is highly weird.

**Comment by chrischu** [comment]
One more test case that might bring some insight into what is going on: When I use the same Ammy UserControl in a ContentPresenter this seems to trigger the bug. In the example solution everything works fine as long as you only press every button only once consecutively (so pressing 1-2-1 is fine, 1-1 is not).

Improved example solution: [DialogHostBug.zip](https://github.com/AmmyUI/AmmyUI/files/853353/DialogHostBug.zip)

**Comment by ionoy** [comment]
Thanks for investigating, I will take a look.

**Comment by ionoy** [comment]
The problem is indeed connected to auto-update feature. There was a bug (fixed already), where `NO_AMMY_UPDATE` didn't have any effect. 

Now to understand why auto-update breaks the dialog host...

**Comment by ionoy** [comment]
Found the issue and fixed it. I will update NuGet packages tomorrow. In the meantime, you can use this compiled `AmmySidekick.dll` where bug is resolved
[AmmySidekick.zip](https://github.com/AmmyUI/AmmyUI/files/853406/AmmySidekick.zip)

**Comment by ionoy** [comment]
Uploaded new version to NuGet. The second sample still doesn't work, but I don't think it's related to Ammy since WPF control also fails to instantiate twice. First sample works properly now.
