### ISSUE TITLE
Problems importing namespaces

### ISSUE THREAD

**Issue by jstaro** [AmmyUI/AmmyUI#7]
I have 3 projects in my solution:
- `SomeApp` (the WPF app lives here, references `SomeApp.Core`)
- `SomeApp.Core`
- `SomeApp.Tests` (references both `SomeApp` and `SomeApp.Core`)

I've Ammy-fied both `App` and `MainWindow`, both live in the root of `SomeApp`
DI is SimpleInjector

in `MainWindow.ammy`, the only _clr-namespace_ I can import things from (by a `using` statement) is
    `SomeApp.Core`

So I can't use any custom controls from my `SomeApp.Controls` namespace.

The only other entries apart from `SomeApp.Core` in the IntelliSense drop-down are
- `SomeApp.App`
- `SomeApp.MainWindow`

Fully qualified name does not work either.

I'm probably doing something wrong.

**Comment by ionoy** [comment]
What assembly contains `SomeApp.Controls`? Do you use latest version of Ammy? (1.1.6) 
Feels like backend doesn't pickup some of the types. There was similar issue today, but that was fixed in 1.1.6 version.

**Comment by jstaro** [comment]
`SomeApp.Controls` is in the `SomeApp` assembly. I'm using 1.1.6 installed today.

**Comment by ionoy** [comment]
Seems like Ammy doesn't pickup your main assembly. Is it an `.exe` or class library? Do you see it in `obj\Debug` directory?

 Is it possible for you to send me simplified version of your project or at least project files? Looks like some configuration error, but I can't figure it out at the moment. 

If it's possible, send it to info@ammyui.com 

Thanks!

**Comment by ionoy** [comment]
I think I have isolated the problem. There is a bug with resolving types from the same assembly. At will probably take me a few days to fix it. Meanwhile you can do following:

1. Comment out "missing" type
2. Compile application
3. Add it back

**Comment by jstaro** [comment]
Since this was an old, pre-existing project I wanted to migrate to using Ammy for evaluation, the setup was a bit wonky.

From what I can tell, this used to be a single assembly application, and then `SomeApp.Core` was extracted into a new assembly, and `SomeApp.Tests` added later on.
So the folder structure was like follows:

```
SomeApp-repo\
  src\
    SomeApp\
      SomeApp.sln       <- these two seemed
      packages\         <- to be the problem
      Controls\
      ViewModels\
        [...]
    SomeApp.Core\
      [...]
    SomeApp.Tests
      [...]
```
When I moved the `.sln` file one step up the folder hierarchy (to `src`), edited the paths in the `.sln`, then removed the `packages` folder, edited all paths referencing the packages folder in all the `.csproj` files, cleaned all outputs and rebuilt the whole solution, then the Ammy designer could import all other namespaces, but I got an `The tag 'CustomTextBox' does not exist in XML namespace 'clr-namespace:SomeApp.Controls;assembly=SomeApp'"` error when trying to build the project anyway.

So I went back to square one, and created 2 minimal, example solutions that exhibit the issue. [The first one](https://github.com/jstaro/ammy-example-1) is created like the above solution, with "Create directory for solution" unchecked, and then I created [the second one](https://github.com/jstaro/ammy-example-2), how you usually tend to structure a multi-project solution.

**Comment by ionoy** [comment]
I read your original comment, thanks for creating sample projects that demonstrate the issue. 

`ammy-example-2-master` actually compiled fine for me
With `ammy-example-1-master` there is an issue I'm currently trying to fix. Unfortunately my recommendations about commenting out missing type wouldn't help. Ammy doesn't differentiate between external references and parent assembly at the moment. And it you actually have to omit assembly when importing namespace from local assembly, so `xmlns:ns0="clr-namespace:SomeApp.CustomControls`, not `xmlns:ns0="clr-namespace:SomeApp.CustomControls;assembly=SomeApp` as it's done now. 

If you are in a hurry, I can create a temporary fix that will generate import attribute correctly. Otherwise new version most likely will be available by tomorrow evening, which will fix everything.

Once again, thanks for helping me understand this issue.

**Comment by jstaro** [comment]
Interesting that `example-2` works for you. I will try it on another machine.
I am not in a hurry, so no need for a temporary fix just for me :)

**Comment by ionoy** [comment]
I was actually able to fix it today. Tried both of your examples, both compile fine now. Uploaded new package to Nuget, so you can try it when you have free time.

**Comment by jstaro** [comment]
Super! Can confirm that it works now.

**Comment by ionoy** [comment]
Great!
