### ISSUE TITLE
Allow passing of constructor arguments

### ISSUE THREAD

**Issue by 99hats** [AmmyUI/AmmyUI#76]
```
<x:Arguments>
    <ListViewCachingStrategy>RecycleElement</ListViewCachingStrategy>
</x:Arguments>
```

**Comment by ionoy** [comment]
I'm thinking something like this:

```
MyControl {
  arguments [
    ListViewCachingStrategy { ... }
  ]
}

```

**Comment by 99hats** [comment]
Looks pretty intuitive to me, should the A in arguments be capped?

**Comment by ionoy** [comment]
All of the current keywords start with the lower-case letter. I think it would be better to continue this way.

**Comment by ionoy** [comment]
I've uploaded fixed version to MyGet, please try if it works for you.

http://www.ammyui.com/documentation/prerelease-builds/

Thanks!

**Comment by 99hats** [comment]
Awesome, works great! Thank you so much.
