### ISSUE TITLE
Allow const members in places where static members are allowed

### ISSUE THREAD

**Issue by roy-t** [AmmyUI/AmmyUI#77]
The following works in XAML but not in Ammy

```
public namespace F
public static class Foo
{         
	public const string SomeString = "Hello, World!";
}
```

Xaml code
`<TextBox Text="{x:Static f:Foo.SomeString}" />`

Ammy equivalent
```
TextBox {
	Text: Foo.SomeString
}
```
The Ammy equivalent fails to compile with the following error

`error : Cannot reference non-static member`

Of course I can change `SomeString` to be `static readonly`, but I think it would still be nice if Ammy supports const members as well :).

_Great project btw! Converting my pet project to AmmyUI as we speak to see if its worth the hassle of convincing the guys at work_

**Comment by ionoy** [comment]
Thanks for kind words!

Will fix it soon.

By the way, if you didn't see, there is a project converter available that makes migrating very easy.

**Comment by ionoy** [comment]
I've uploaded fixed version to MyGet, please try if it works for you.

http://www.ammyui.com/documentation/prerelease-builds/

Thanks!

**Comment by roy-t** [comment]
Wow, that's great! I'll check it out tomorrow and let you know if it works :).

**Comment by roy-t** [comment]
Seems to work great, thanks for the change!
