### ISSUE TITLE
Ammy Compilation Error

### ISSUE THREAD

**Issue by jacoblangston** [AmmyUI/AmmyUI#8]
I receive this error when attempting to build with Ammy files in a solution.  The issue appears to occur when a 32 bit dll is referenced in a solution that has a configuration of Any CPU.

2><Default>(1,1,1,1): error : Ammy compilation error: System.NullReferenceException: Object reference not set to an instance of an object.
2><Default>(1,1,1,1): error :    at Ammy.Language.Start.GetPublicStaticProperties(TypeSymbol ts)
2><Default>(1,1,1,1): error :    at Ammy.Language.Start.PrepareScopes(NamespaceSymbol rootNamespace, AmmyDependentPropertyEvalContext context)
2><Default>(1,1,1,1): error :    at Ammy.Language.Start.RefreshReferences(Project project)
2><Default>(1,1,1,1): error :    at Ammy.Language.Start.RefreshReferences(CancellationToken _cancellationToken, Project project)
2><Default>(1,1,1,1): error :    at Ammy.Build.AmmyProject.RefreshReferences()
2><Default>(1,1,1,1): error :    at Ammy.Build.AmmyCompiler.Compile(AmmyProject project, Boolean generateMetaFile, Boolean needBamlGeneration, Boolean needUpdate)

**Comment by ionoy** [comment]
Thanks, I will get to it as soon as possible.

**Comment by ionoy** [comment]
Is it possible for you to send me dll in question? I've compiled 32 bit assembly, checked that it indeed requires 32bit, but Ammy still compiles fine after referencing it.

Also, is host project WPF? Seems like some types were not loaded, like `System.Windows.Media.Brushes` etc.

**Comment by ionoy** [comment]
Would you be able to send me copy of your project? With all sources removed of course, since I only need configuration.

**Comment by jacoblangston** [comment]
Yes, the dll causing issues is LeadTools.  An evaluation copy can be downloaded from https://www.leadtools.com/downloads?category=mm.

Here is the error with LeadTools included in the project.  I had removed LeadTools from the solution when I sent the earlier error, and I was getting it from another project.

1>  All packages listed in C:\git\aceclient\CapitalGroup.Afsd.Desktop\packages.config are already installed.
1><Default>(1,1,1,1): error : Ammy compilation error: System.IO.FileLoadException: Could not load file or assembly 'Leadtools.Barcode, Version=19.0.4.0, Culture=neutral, PublicKeyToken=9cf889f53ea9b907' or one of its dependencies. Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x80131019)
1><Default>(1,1,1,1): error : File name: 'Leadtools.Barcode, Version=19.0.4.0, Culture=neutral, PublicKeyToken=9cf889f53ea9b907' ---> System.IO.FileLoadException: Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x80131019)
1><Default>(1,1,1,1): error :    at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, SecurityContextSource securityContextSource)
1><Default>(1,1,1,1): error :    at System.Reflection.Assembly.Load(Byte[] rawAssembly)
1><Default>(1,1,1,1): error :    at Ammy.Backend.ReflectionBackend.LoadExternalSymbols(IEnumerable`1 libs, String libPath, ICompilerMessages compilerMessages, DependentPropertyEvalContext context)
1><Default>(1,1,1,1): error :    at Ammy.Language.Start.RefreshReferences(Project project)
1><Default>(1,1,1,1): error :    at Ammy.Language.Start.RefreshReferences(CancellationToken _cancellationToken, Project project)
1><Default>(1,1,1,1): error :    at Ammy.Build.AmmyProject.RefreshReferences()
1><Default>(1,1,1,1): error :    at Ammy.Build.AmmyCompiler.Compile(AmmyProject project, Boolean generateMetaFile, Boolean needBamlGeneration, Boolean needUpdate)
1><Default>(1,1,1,1): error : 
1><Default>(1,1,1,1): error : 
1>C:\git\aceclient\packages\Ammy.1.1.8\build\Ammy.targets(15,5): error : Ammy compilation failed

**Comment by jacoblangston** [comment]
The error I sent previously I received after I removed LeadTools from the solution, and it was stopping on x86 projects and my Windows Installer XML project.

**Comment by ionoy** [comment]
I've added some error checking to backend. Could you try if it works for you now? 
Just copy `Ammy.Backend.dll` to `packages\Ammy.1.1.*\build\`

[Ammy.Backend.zip](https://github.com/AmmyUI/AmmyUI/files/711657/Ammy.Backend.zip)

**Comment by jacoblangston** [comment]
Yes, working on it.  I'll get back to you in a few hours.

**Comment by ionoy** [comment]
Seems like an issue with an indirectly referenced assembly. I've modified assembly resolver to accommodate for that. It works in my test cases. Please test it in your configuration.

[Ammy.Backend.zip](https://github.com/AmmyUI/AmmyUI/files/711932/Ammy.Backend.zip)

**Comment by jacoblangston** [comment]
Better.  I get this error now:
1><Default>(1,1,1,1): error : Ammy compilation error: System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long
1><Default>(1,1,1,1): error :    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1><Default>(1,1,1,1): error :    at System.Diagnostics.Process.Start()
1><Default>(1,1,1,1): error :    at Ammy.Build.BamlCompiler.CompileBamlFiles(CompileResult result, AmmyProject project)
1><Default>(1,1,1,1): error :    at Ammy.Build.AmmyCompiler.Compile(AmmyProject project, Boolean generateMetaFile, Boolean needBamlGeneration, Boolean needUpdate)
1>C:\git\aceclient\packages\Ammy.1.1.8\build\Ammy.targets(15,5): error : Ammy compilation failed

**Comment by ionoy** [comment]
Could you copy build output from Output window? 
It needs to be setup for verbose output:
Tools > Options > Projects and Solutions > Build and Run > MSBuild project build output verbosity: Diagnostic

Sorry you encountered so many issues. Your report already helped to resolve two of them, so thank you!

**Comment by ionoy** [comment]
You can send build output to info@ammyui.com if you can't to post it publicly. Thanks!

**Comment by jacoblangston** [comment]
Yes.  I'll get it to you tomorrow.  I've been in meetings all day.

**Comment by ionoy** [comment]
Any news? Also, please update to latest version from MyGet

Nuget V3: https://www.myget.org/F/ammy/api/v3/index.json
Nuget V2: https://www.myget.org/F/ammy/api/v2

Add it to Options -> Nuget Package Manager -> Package Sources
Don't forget to click Update button there.

After that just switch Package Manager source to this new feed and update-package Ammy. You might need to restart visual studio, since it uses assemblies from a package.

**Comment by jacoblangston** [comment]
Okay.  Updated to Ammy 1.1.19.

Here is the output when i try to compile the project.  I changed the project name to be different but to have the same length of the actual name.
1>------ Build started: Project: Abcdefghijkl.Abcd.Desktop, Configuration: Debug Any CPU ------
1>  Restoring NuGet packages...
1>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
1>  Feeds used:
1>    C:\Users\abcd\AppData\Local\NuGet\Cache
1>    C:\Users\abcd\.nuget\packages\
1>    https://api.nuget.org/v3/index.json
1>  
1>  All packages listed in C:\git\abcclient\Abcdefghijkl.Abcd.Desktop\packages.config are already installed.
1><Default>(1,1,1,1): error : Ammy compilation error: System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long
1><Default>(1,1,1,1): error :    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1><Default>(1,1,1,1): error :    at System.Diagnostics.Process.Start()
1><Default>(1,1,1,1): error :    at Ammy.Build.BamlCompiler.CompileBamlFiles(CompileResult result, AmmyProject project)
1><Default>(1,1,1,1): error :    at Ammy.Build.AmmyCompiler.Compile(AmmyProject project, Boolean generateMetaFile, Boolean needBamlGeneration, Boolean needUpdate)
1>C:\git\abcclient\packages\Ammy.1.1.19\build\Ammy.targets(15,5): error : Ammy compilation failed
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by ionoy** [comment]
Can you try compiling using updated Ammy.Build.dll? It will output a warning with full path and arguments to bamlcwpf.exe

Thanks!

[Ammy.Build.zip](https://github.com/AmmyUI/AmmyUI/files/730124/Ammy.Build.zip)

**Comment by jacoblangston** [comment]
I emailed you the output.

**Comment by ionoy** [comment]
Sorry for taking so long!

It was an issue with windows not able to handle really long command line arguments. I resolved it by writing arguments into file and using that as a source.

New version is uploaded to NuGet, please check if it finally resolves your issue.

Thanks for your patience :)

**Comment by jacoblangston** [comment]
Great!  I'll test it this afternoon.

**Comment by jacoblangston** [comment]
The latest version I see is still 1.1.19.

**Comment by ionoy** [comment]
You will have to use MyGet feed as I have described earlier. I will put it on NuGet as soon as it's confirmed working.

Here are instructions for configuring MyGet feed:

Nuget V3: https://www.myget.org/F/ammy/api/v3/index.json
Nuget V2: https://www.myget.org/F/ammy/api/v2

Add it to Options -> Nuget Package Manager -> Package Sources
Don't forget to click Update button there.

After that just switch Package Manager source to this new feed and update-package Ammy. You might need to restart visual studio, since it uses assemblies from a package.

**Comment by jacoblangston** [comment]
Better :).  I now see this error.

1><Default>(1,1,1,1): error : Ammy compilation error: Nemerle.Core.AssertionException: assertion failed in file Type\Member\Member.nitra, line 83: Property 'DotNet.Member.PropertySymbol.Type' is not set'
1><Default>(1,1,1,1): error :    at DotNet.Member.PropertySymbol.get_Type()
1><Default>(1,1,1,1): error :    at Ammy.Backend.XamlSymbolLoader.LoadType(SupportsInheritanceTypeSymbol type, TypeSymbol objectType, DependentPropertyEvalContext context, PlatformTypeNames platformTypeNames)
1><Default>(1,1,1,1): error :    at Ammy.Backend.CSharpBackend._N_registerParsedTypes_12541(_N_closureOf_Load_12499 _N_Load_cp_12540, TableScope tableScope)
1><Default>(1,1,1,1): error :    at Ammy.Backend.CSharpBackend._N_registerParsedTypes_12541(_N_closureOf_Load_12499 _N_Load_cp_12540, TableScope tableScope)
1><Default>(1,1,1,1): error :    at Ammy.Backend.CSharpBackend._N_registerParsedTypes_12541(_N_closureOf_Load_12499 _N_Load_cp_12540, TableScope tableScope)
1><Default>(1,1,1,1): error :    at Ammy.Backend.CSharpBackend._N_registerParsedTypes_12541(_N_closureOf_Load_12499 _N_Load_cp_12540, TableScope tableScope)
1><Default>(1,1,1,1): error :    at Ammy.Backend.CSharpBackend._N_registerParsedTypes_12541(_N_closureOf_Load_12499 _N_Load_cp_12540, TableScope tableScope)
1><Default>(1,1,1,1): error :    at Ammy.Backend.CSharpBackend._N_registerParsedTypes_12541(_N_closureOf_Load_12499 _N_Load_cp_12540, TableScope tableScope)
1><Default>(1,1,1,1): error :    at Ammy.Backend.CSharpBackend.Load(ISourceCodeProject project, NamespaceSymbol globalNamespace, TypeSymbol objectType, PlatformTypeNames platformTypeNames, DependentPropertyEvalContext context)
1><Default>(1,1,1,1): error :    at Ammy.Language.Start.RefreshProject(CancellationToken _cancellationToken, ImmutableArray`1 files, Object data)
1><Default>(1,1,1,1): error :    at Ammy.Build.AmmyProject.RefreshProject(String outputPath, String rootNamespace, String assemblyName)
1><Default>(1,1,1,1): error :    at Ammy.Build.AmmyCompiler.Compile(AmmyProject project, Boolean generateMetaFile, Boolean needBamlGeneration, Boolean needUpdate)
1>C:\git\abcclient\packages\Ammy.1.1.25\build\Ammy.targets(15,5): error : Ammy compilation failed

**Comment by ionoy** [comment]
Alright, I've updated it again, try it once more, please :)

**Comment by jacoblangston** [comment]
It now compiles.  Thank you for being so responsive in resolving these issues!
