### ISSUE TITLE
Support inline comments

### ISSUE THREAD

**Issue by theweavrs** [AmmyUI/AmmyUI#84]
Ammy should have support for inline comments. The syntax could be the same as C# or perhaps `{{ comment here }}`? Aside from inline comments, there should also be support for block comments (you know `/* comment here */`).

Anything commented out could either be ignored altogether or converted to XAML comment.

**Comment by ionoy** [comment]
Ammy already has both C-style comments:

```
TextBlock {
  // Width: 100
  /* Background: Red */
}
```

**Comment by theweavrs** [comment]
@ionoy ah good. Sorry for a useless issue then :)

**Comment by chizran** [comment]
Perhaps I should open, however there is a problem with the current implementation of comments.
When using Ammy's formatting document option, the comments get deleted. Maybe they could be converted to XAML comments and kept when formatting the document?

**Comment by ionoy** [comment]
This is more of a problem with document formatter than comments. I think it deserves a separate issue.
