### ISSUE TITLE
Unable to combine mixins for grid columns definition

### ISSUE THREAD

**Issue by isukces** [AmmyUI/AmmyUI#87]
I try to define grid with 7 columns using  following syntax but it is not accepted by Ammy compiler
```
Grid { 
    #FiveColumns("Auto","Auto","Auto","Auto","Auto")
    #TwoColumns("Auto","Auto")
}
```

**Comment by ionoy** [comment]
This is a bug. 

Meanwhile you can extend Grid definitions up to Ten. We could even put that into main repository. https://github.com/AmmyUI/AmmyUI/blob/master/src/AmmyStandardLib/lib-wpf.ammy

**Comment by ionoy** [comment]
This should be fixed now https://github.com/AmmyUI/AmmyUI/commit/6c78c55d2b6cbaadd73ba14a8e972788d825ff3b

The current version is still on MyGet though, I will soon upload it to NuGet.
