### ISSUE TITLE
 Nemerle.Core.AssertionException: assertion !IsMemberTableEvaluated

### ISSUE THREAD

**Issue by isukces** [AmmyUI/AmmyUI#88]
I get following compilation error:
Ammy compilation error: Nemerle.Core.AssertionException: assertion ``!IsMemberTableEvaluated'' failed in file C:\Users\mihha\Documents\GitHub\Ammy\lib\Nitra\bin\Debug\Stage1\Nitra.Runtime.dll, line 1: Property 'MemberTable' is already set.

Problem occurs when ammy control has additional partial cs file with some members (dependency properties in my case).
When stuff was moved to mycontrol.ammy.cs and additional cs file was deleted - problem dissapeard.

**Comment by ionoy** [comment]
Weird... Is this class marked with `partial` modifier?

**Comment by isukces** [comment]
Yes. Maybe it matters but one part is in different folder on disk but still in the same project and of course the same namespace.

**Comment by ionoy** [comment]
This should be fixed now. Please, try updating from NuGet.

Thanks!
