### ISSUE TITLE
VS2017 Window Focus Issue

### ISSUE THREAD

**Issue by siada** [AmmyUI/AmmyUI#90]
When editing ammy files visual studio will randomly lose focus to something for about 3 - 5 seconds and then regain focus, almost as if its off doing some validation or something. 

This is really frustrating because it won't continue to type anything until the focus comes back(either by itself or manually re-selecting Visual Studio).

I'm using Vs2017

**Comment by ionoy** [comment]
This is actually the first time I'm hearing about this. Are you sure this issue is caused by Ammy?

**Comment by siada** [comment]
It only happens in ammy files, C# files are fine, anything else I've tested is fine. I can't exactly confirm for sure if it is ammy, but it seems the most likely culprit.

**Comment by roy-t** [comment]
I can only say that I do not have this issue with Ammy files, what plugins do you have installed? (I'm using Resharper and the Productivity Power Tools, they seem to be fine).

**Comment by siada** [comment]
I only have resharper installed, apart from that its a completely fresh 2017 installation

**Comment by siada** [comment]
Updated from base 2017 to the latest version of 2017 and the issue seems to have gone away.
