### ISSUE TITLE
NuGet package licenses out of date

### ISSUE THREAD

**Issue by kalderman** [AmmyUI/AmmyUI#99]
The license in your source is MIT, yet the nuget packages link to a non-commercial license 
https://creativecommons.org/licenses/by-nc/3.0/

This is causing confusion and is in conflict with your blog post stating that AmmyUI is free for commercial use.

**Comment by WasserEsser** [comment]
I guess this can be closed, @ionoy?

**Comment by ionoy** [comment]
I guess so. Although, the new package is not uploaded yet.
